# Generated by Django 5.0.14 on 2025-04-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookpage',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_review',
        ),
    ]
