# Generated by Django 5.0.14 on 2025-04-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_book_bookpage_remove_book_total_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='stock',
            new_name='items_sold',
        ),
    ]
